name = "quantum-skies"
author = "jmoiron"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2af9f2c77709178ffb6d53ab1f1534ffe632ddc6974b7852f63093e3ec83c680"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
