name = "quantum-skies"
author = "jmoiron"
version = "0.7.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0443826d08bec5d4512d078041ab4a94fdd5dc2ebc5e40abfbaf1761f22b0da7"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
